spring:
  application:
    name: mall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST:192.168.5.29}:${DB_PORT:3306}/mall?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
server:
  port: 8081
